kind: pipeline
name: default

steps:
  - name: fetch
    image: node:latest
    commands:
    - git fetch --tags

  - name: build
    image: node:latest
    commands:
      - npm install

  - name: generate-releaselog
    image: node:latest
    environment:
      CONVENTIONAL_GITHUB_RELEASER_TOKEN:
        from_secret: CONVENTIONAL_GITHUB_RELEASER_TOKEN
    commands:
      - npm run generate-releaselog
    when:
      event: tag